# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy static website files to the default Nginx HTML directory
COPY Blog/html /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80